apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook-weight: "0"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: init-sleep
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-sleep
        image: busybox:1.28
        command: ['sh', '-c', 'sleep 20']
